// This file is generated by kconfig_compiler from 802-11-wireless.kcfg.
// All changes you do to this file will be lost.

#include "802-11-wireless.h"

using namespace KnmInternals;

WirelessSetting::WirelessSetting() : Setting(Setting::Wireless),
    mMode(0), mBand(WirelessSetting::EnumBand::bg), mChannel(0), mRate(0), mTxpower(0), mMtu(0)
{
}

WirelessSetting::~WirelessSetting()
{
}

QString WirelessSetting::name() const
{
  return QLatin1String("802-11-wireless");
}
bool WirelessSetting::hasSecrets() const
{
  return false;
}
