// This file is generated by kconfig_compiler from 802-11-wireless-security.kcfg.
// All changes you do to this file will be lost.
#ifndef KNMINTERNALS_WIRELESSSECURITYDBUS_H
#define KNMINTERNALS_WIRELESSSECURITYDBUS_H

#include <nm-setting-wireless-security.h>

#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "settingdbus.h"
#include "knm_export.h"
namespace KnmInternals {

class WirelessSecuritySetting;

class KNM_EXPORT WirelessSecurityDbus : public SettingDbus
{
  public:
    WirelessSecurityDbus(WirelessSecuritySetting * setting, const QString & essid);
    ~WirelessSecurityDbus();
    void fromMap(const QVariantMap&);
    QVariantMap toMap();
    QVariantMap toSecretsMap();
  private:
    QString hashWpaPsk(const QString & plainText);
    QString hashWepPassphrase(const QString & plainText);
    QString m_essid;
};
}

#endif

