// This file is generated by kconfig_compiler from cdma.kcfg.
// All changes you do to this file will be lost.

#include "cdma.h"
#include "cdmasecrets.h"

using namespace Knm;

CdmaSetting::CdmaSetting() : Setting(Setting::Cdma)
{
    m_secretsObject = new CdmaSecrets(this);
}

CdmaSetting::CdmaSetting(CdmaSetting *setting) : Setting(setting)
{
    m_secretsObject = new CdmaSecrets(static_cast<CdmaSecrets*>(setting->getSecretsObject()), this);
    setNumber(setting->number());
    setUsername(setting->username());
    setPassword(setting->password());
    setPasswordflags(setting->passwordflags());
}

CdmaSetting::~CdmaSetting()
{
}

QString CdmaSetting::name() const
{
  return QLatin1String("cdma");
}
bool CdmaSetting::hasSecrets() const
{
  return true;
}
void CdmaSetting::setSecrets(Setting::secretsTypes types)
{
    if (!mPassword.isEmpty())
        setPasswordflags(types);
}
