// This file is generated by kconfig_compiler from gsm.kcfg.
// All changes you do to this file will be lost.

#include "gsm.h"
#include "gsmsecrets.h"

using namespace Knm;

GsmSetting::GsmSetting() : Setting(Setting::Gsm), mNetworktype(-1), mBand(-1)
{
    m_secretsObject = new GsmSecrets(this);
}

GsmSetting::~GsmSetting()
{
}

QString GsmSetting::name() const
{
  return QLatin1String("gsm");
}
bool GsmSetting::hasSecrets() const
{
  return true;
}
void GsmSetting::setSecrets(Setting::secretsTypes types)
{
    if (!mPassword.isEmpty())
        setPasswordflags(types);
    if (!mPin.isEmpty())
        setPinflags(types);
}
