// This file is generated by kconfig_compiler from ipv4.kcfg.
// All changes you do to this file will be lost.

#include "ipv4.h"

using namespace Knm;

Ipv4Setting::Ipv4Setting() : Setting(Setting::Ipv4),
    mMethod(Ipv4Setting::EnumMethod::Automatic),
    mIgnoredhcpdns(false)
{
}

Ipv4Setting::~Ipv4Setting()
{
}

QString Ipv4Setting::name() const
{
  return QLatin1String("ipv4");
}
bool Ipv4Setting::hasSecrets() const
{
  return false;
}
