// This file is generated by kconfig_compiler from pppoe.kcfg.
// All changes you do to this file will be lost.

#include "pppoe.h"

using namespace KnmInternals;

PppoeSetting::PppoeSetting() : Setting(Setting::Pppoe)
{
}

PppoeSetting::~PppoeSetting()
{
}

QString PppoeSetting::name() const
{
  return QLatin1String("pppoe");
}
bool PppoeSetting::hasSecrets() const
{
  return true;
}
