// This file is generated by kconfig_compiler from vpn.kcfg.
// All changes you do to this file will be lost.

#include "vpn.h"

using namespace Knm;

VpnSetting::VpnSetting() : Setting(Setting::Vpn)
{
  mSecretsStorageType = QStringMap();
}

VpnSetting::VpnSetting(VpnSetting *setting) : Setting(setting)
{
    setServiceType(setting->serviceType());
    setData(setting->data());
    setUserName(setting->userName());
    setVpnSecrets(setting->vpnSecrets());
    setPluginName(setting->pluginName());
    setSecretsStorageType(setting->secretsStorageType());
}

VpnSetting::~VpnSetting()
{
}

QString VpnSetting::name() const
{
  return QLatin1String("vpn");
}
bool VpnSetting::hasSecrets() const
{
  return true;
}

bool VpnSetting::hasVolatileSecrets() const
{
  foreach(const QString & s, mSecretsStorageType.keys())
    if (mSecretsStorageType.value(s) == QLatin1String(NM_VPN_PW_TYPE_ASK))
      return true;

  return false;
}
