// This file is generated by kconfig_compiler from 802-3-ethernet.kcfg.
// All changes you do to this file will be lost.
#ifndef WIREDDBUS_H
#define WIREDDBUS_H

#include <nm-setting-wired.h>

#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "settingdbus.h"
#include "nm09dbus_export.h"
namespace Knm{
    class WiredSetting;
}

class NM09DBUS_EXPORT WiredDbus : public SettingDbus
{
  public:
    WiredDbus(Knm::WiredSetting * setting);
    ~WiredDbus();
    void fromMap(const QVariantMap&);
    QVariantMap toMap();
    QVariantMap toSecretsMap();
};
#endif

