// This file is generated by kconfig_compiler from ppp.kcfg.
// All changes you do to this file will be lost.
#ifndef PPPDBUS_H
#define PPPDBUS_H

#include <nm-setting-ppp.h>

#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "settingdbus.h"
#include "nm07dbus_export.h"
namespace Knm{
    class PppSetting;
}

class NM07DBUS_EXPORT PppDbus : public SettingDbus
{
  public:
    PppDbus(Knm::PppSetting * setting);
    ~PppDbus();
    void fromMap(const QVariantMap&);
    QVariantMap toMap();
    QVariantMap toSecretsMap();
  private:
    void insertIfTrue(QVariantMap& map, const char * key, bool setting);
    void insertIfNonZero(QVariantMap& map, const char * key, uint setting);
};
#endif

