/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a exportedconnectionsecrets -N -i marshalarguments.h -i types.h -i busconnection.h -l BusConnection -c SecretsAdaptor introspection/nm-connection-secrets.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef EXPORTEDCONNECTIONSECRETS_H
#define EXPORTEDCONNECTIONSECRETS_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "marshalarguments.h"
#include "types.h"
#include "busconnection.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.NetworkManagerSettings.Connection.Secrets
 */
class SecretsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManagerSettings.Connection.Secrets")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManagerSettings.Connection.Secrets\">\n"
"    <tp:docstring>\n"
"            Secrets have a separate interface so that they can be locked down.\n"
"        </tp:docstring>\n"
"    <method name=\"GetSecrets\">\n"
"      <tp:docstring>\n"
"                Get the secrets encapsulated in this object.\n"
"            </tp:docstring>\n"
"      <annotation value=\"impl_exported_connection_get_secrets\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"setting_name\">\n"
"        <tp:docstring>\n"
"                    Name of the setting to return.\n"
"                </tp:docstring>\n"
"      </arg>\n"
"      <arg direction=\"in\" type=\"as\" name=\"hints\">\n"
"        <tp:docstring>\n"
"                    Array of strings of key names in the Setting for which NM thinks\n"
"                    a secrets may be required.\n"
"                </tp:docstring>\n"
"      </arg>\n"
"      <arg direction=\"in\" type=\"b\" name=\"request_new\">\n"
"        <tp:docstring>\n"
"                    Indicates whether new secrets should be requested or if the request can be fulfilled from storage.\n"
"                </tp:docstring>\n"
"      </arg>\n"
"      <arg direction=\"out\" tp:type=\"String_String_Variant_Map_Map\" type=\"a{sa{sv}}\" name=\"secrets\">\n"
"        <annotation value=\"QVariantMapMap\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"        <tp:docstring>\n"
"                    Nested settings maps containing secrets.  Each setting MUST contain at least the 'name' field, containing the name of the setting, and one or more secrets.\n"
"                </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SecretsAdaptor(BusConnection *parent);
    virtual ~SecretsAdaptor();

    inline BusConnection *parent() const
    { return static_cast<BusConnection *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QVariantMapMap GetSecrets(const QString &setting_name, const QStringList &hints, bool request_new, const QDBusMessage &);
Q_SIGNALS: // SIGNALS
};

#endif
