/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i types.h -N -p nm-ip4-config-interface introspection/nm-ip4-config.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef NM_IP4_CONFIG_INTERFACE_H
#define NM_IP4_CONFIG_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "types.h"

// Need ito export the class to use it externally (in the applet)
#include "knm_export.h"

/*
 * Proxy class for interface org.freedesktop.NetworkManager.IP4Config
 */
class KNM_EXPORT OrgFreedesktopNetworkManagerIP4ConfigInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.NetworkManager.IP4Config"; }

public:
    OrgFreedesktopNetworkManagerIP4ConfigInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopNetworkManagerIP4ConfigInterface();

    Q_PROPERTY(QList<QList<uint> > Addresses READ addresses)
    inline QList<QList<uint> > addresses() const
    { return qvariant_cast< QList<QList<uint> > >(property("Addresses")); }

    Q_PROPERTY(QStringList Domains READ domains)
    inline QStringList domains() const
    { return qvariant_cast< QStringList >(property("Domains")); }

    Q_PROPERTY(QList<uint> Nameservers READ nameservers)
    inline QList<uint> nameservers() const
    { return qvariant_cast< QList<uint> >(property("Nameservers")); }

    Q_PROPERTY(QList<QList<uint> > Routes READ routes)
    inline QList<QList<uint> > routes() const
    { return qvariant_cast< QList<QList<uint> > >(property("Routes")); }

    Q_PROPERTY(QList<uint> WinsServers READ winsServers)
    inline QList<uint> winsServers() const
    { return qvariant_cast< QList<uint> >(property("WinsServers")); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
