/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -N -m -p nm-settingsinterface /space/kde/sources/trunk/playground/base/plasma/applets/networkmanager/settings/dbus/introspection/nm-settings.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-settingsinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerSettingsInterface
 */

OrgFreedesktopNetworkManagerSettingsInterface::OrgFreedesktopNetworkManagerSettingsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerSettingsInterface::~OrgFreedesktopNetworkManagerSettingsInterface()
{
}


#include "nm-settingsinterface.moc"
