/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -m -p connectioninterface /home/jackrabbit/kde/src/KDE/base/plasma/applets/networkmanager/settings/dbus/introspection/nm-settings-connection.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "connectioninterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerSettingsConnectionInterface
 */

OrgFreedesktopNetworkManagerSettingsConnectionInterface::OrgFreedesktopNetworkManagerSettingsConnectionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerSettingsConnectionInterface::~OrgFreedesktopNetworkManagerSettingsConnectionInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerSettingsConnectionSecretsInterface
 */

OrgFreedesktopNetworkManagerSettingsConnectionSecretsInterface::OrgFreedesktopNetworkManagerSettingsConnectionSecretsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerSettingsConnectionSecretsInterface::~OrgFreedesktopNetworkManagerSettingsConnectionSecretsInterface()
{
}


#include "connectioninterface.moc"
