// This file is generated by kconfig_compiler from 802-11-wireless.kcfg.
// All changes you do to this file will be lost.

#include "802-11-wirelesspersistence.h"

#include "802-11-wireless.h"

WirelessPersistence::WirelessPersistence(WirelessSetting * setting, KSharedConfig::Ptr config) : SettingPersistence(setting, config)
{
}

WirelessPersistence::~WirelessPersistence()
{
}

void WirelessPersistence::load()
{
  WirelessSetting * setting = static_cast<WirelessSetting *>(m_setting);
  setting->setSsid(m_config->readEntry("ssid", QByteArray()));
  // SECRET
  setting->setMode(m_config->readEntry("mode", 0));
  setting->setBand(m_config->readEntry("band", 1));
  setting->setChannel(m_config->readEntry("channel", 0));
  setting->setBssid(m_config->readEntry("bssid", QByteArray()));
  setting->setRate(m_config->readEntry("rate", 0));
  setting->setTxpower(m_config->readEntry("txpower", 0));
  setting->setMacaddress(m_config->readEntry("macaddress", QByteArray()));
  setting->setMtu(m_config->readEntry("mtu", 1500));
  setting->setSeenbssids(m_config->readEntry("seenbssids", QStringList()));
  setting->setSecurity(m_config->readEntry("security", ""));
}

void WirelessPersistence::save()
{
  WirelessSetting * setting = static_cast<WirelessSetting *>(m_setting);
  m_config->writeEntry("ssid", setting->ssid());
  // SECRET
  m_config->writeEntry("mode", setting->mode());
  m_config->writeEntry("band", setting->band());
  m_config->writeEntry("channel", setting->channel());
  m_config->writeEntry("bssid", setting->bssid());
  m_config->writeEntry("rate", setting->rate());
  m_config->writeEntry("txpower", setting->txpower());
  m_config->writeEntry("macaddress", setting->macaddress());
  m_config->writeEntry("mtu", setting->mtu());
  m_config->writeEntry("seenbssids", setting->seenbssids());
  m_config->writeEntry("security", setting->security());
}

