// This file is generated by kconfig_compiler from 802-1x.kcfg.
// All changes you do to this file will be lost.
#ifndef KNM_INTERNALS_SECURITY8021XPERSISTENCE_H
#define KNM_INTERNALS_SECURITY8021XPERSISTENCE_H

#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "settingpersistence.h"
#include "knm_export.h"
namespace Knm {

class Security8021xSetting;

class KNM_EXPORT Security8021xPersistence : public SettingPersistence
{
  public:
    Security8021xPersistence( Security8021xSetting * setting, KSharedConfig::Ptr config, ConnectionPersistence::SecretStorageMode mode = ConnectionPersistence::Secure);
    ~Security8021xPersistence();
    void load();
    void save();
    QMap<QString,QString> secrets() const;
    void restoreSecrets(QMap<QString,QString>) const;
};
}

#endif

