// This file is generated by kconfig_compiler from 802-11-wireless.kcfg.
// All changes you do to this file will be lost.

#include "802-11-wirelessdbus.h"

#include "802-11-wireless.h"

using namespace Knm;

WirelessDbus::WirelessDbus(WirelessSetting * setting) : SettingDbus(setting)
{
}

WirelessDbus::~WirelessDbus()
{
}

void WirelessDbus::fromMap(const QVariantMap & map)
{
  WirelessSetting * setting = static_cast<WirelessSetting *>(m_setting);
  if (map.contains("ssid")) {
    setting->setSsid(map.value("ssid").value<QByteArray>());
  }
  if (map.contains("mode")) {
    setting->setMode(map.value("mode").value<int>());
  }
  if (map.contains("band")) {
    setting->setBand(map.value("band").value<int>());
  }
  if (map.contains("channel")) {
    setting->setChannel(map.value("channel").value<uint>());
  }
  if (map.contains("bssid")) {
    setting->setBssid(map.value("bssid").value<QByteArray>());
  }
  if (map.contains("rate")) {
    setting->setRate(map.value("rate").value<uint>());
  }
  if (map.contains(QLatin1String(NM_SETTING_WIRELESS_TX_POWER))) {
    setting->setTxpower(map.value(QLatin1String(NM_SETTING_WIRELESS_TX_POWER)).value<uint>());
  }
  if (map.contains(QLatin1String(NM_SETTING_WIRELESS_MAC_ADDRESS))) {
    setting->setMacaddress(map.value(QLatin1String(NM_SETTING_WIRELESS_MAC_ADDRESS)).value<QByteArray>());
  }
  if (map.contains("mtu")) {
    setting->setMtu(map.value("mtu").value<uint>());
  }
  if (map.contains(QLatin1String(NM_SETTING_WIRELESS_SEEN_BSSIDS))) {
    setting->setSeenbssids(map.value(QLatin1String(NM_SETTING_WIRELESS_SEEN_BSSIDS)).value<QStringList>());
  }
  // SECRET
  if (map.contains("security")) {
    setting->setSecurity(map.value("security").value<QString>());
  }
}

QVariantMap WirelessDbus::toMap()
{
  QVariantMap map;
  WirelessSetting * setting = static_cast<WirelessSetting *>(m_setting);
  map.insert("ssid", setting->ssid());
  map.insert("mode", setting->mode());
  map.insert("band", setting->band());
  map.insert("channel", setting->channel());
  map.insert("bssid", setting->bssid());
  map.insert("rate", setting->rate());
  map.insert(QLatin1String(NM_SETTING_WIRELESS_TX_POWER), setting->txpower());
  map.insert(QLatin1String(NM_SETTING_WIRELESS_MAC_ADDRESS), setting->macaddress());
  map.insert("mtu", setting->mtu());
  map.insert(QLatin1String(NM_SETTING_WIRELESS_SEEN_BSSIDS), setting->seenbssids());
  return map;
}

QVariantMap WirelessDbus::toSecretsMap()
{
  QVariantMap map;
  WirelessSetting * setting = static_cast<WirelessSetting *>(m_setting);
  map.insert("name", setting->name());
  map.insert("security", setting->security());
  return map;
}

