// This file is generated by kconfig_compiler from 802-11-wireless.kcfg.
// All changes you do to this file will be lost.
#ifndef KNMINTERNALS_WIRELESSPERSISTENCE_H
#define KNMINTERNALS_WIRELESSPERSISTENCE_H

#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "settingpersistence.h"
#include "knm_export.h"
namespace KnmInternals {

class WirelessSetting;

class KNM_EXPORT WirelessPersistence : public SettingPersistence
{
  public:
    WirelessPersistence( WirelessSetting * setting, KSharedConfig::Ptr config, ConnectionPersistence::SecretStorageMode mode = ConnectionPersistence::Secure);
    ~WirelessPersistence();
    void load();
    void save();
    QMap<QString,QString> secrets() const;
    void restoreSecrets(QMap<QString,QString>) const;
};
}

#endif

