// This file is generated by kconfig_compiler from 802-11-wireless.kcfg.
// All changes you do to this file will be lost.

#include "802-11-wireless.h"

WirelessSetting::WirelessSetting() : Setting(Setting::Wireless)
{
}

WirelessSetting::~WirelessSetting()
{
}

QString WirelessSetting::name() const
{
  return QLatin1String("802-11-wireless");
}
