// This file is generated by kconfig_compiler from 802-3-ethernet.kcfg.
// All changes you do to this file will be lost.

#include "802-3-ethernetpersistence.h"

#include "802-3-ethernet.h"

using namespace Knm;

WiredPersistence::WiredPersistence(WiredSetting * setting, KSharedConfig::Ptr config, ConnectionPersistence::SecretStorageMode mode) : SettingPersistence(setting, config, mode)
{
}

WiredPersistence::~WiredPersistence()
{
}

void WiredPersistence::load()
{
  WiredSetting * setting = static_cast<WiredSetting *>(m_setting);
  setting->setPort(m_config->readEntry("port", 0));
  setting->setSpeed(m_config->readEntry("speed", 0));
  setting->setDuplex(m_config->readEntry("duplex", 0));
  setting->setAutonegotiate(m_config->readEntry("autonegotiate", true));
  setting->setMacaddress(m_config->readEntry("macaddress", QByteArray()));
  setting->setMtu(m_config->readEntry("mtu", 0));
}

void WiredPersistence::save()
{
  WiredSetting * setting = static_cast<WiredSetting *>(m_setting);
  m_config->writeEntry("port", setting->port());
  m_config->writeEntry("speed", setting->speed());
  m_config->writeEntry("duplex", setting->duplex());
  m_config->writeEntry("autonegotiate", setting->autonegotiate());
  m_config->writeEntry("macaddress", setting->macaddress());
  m_config->writeEntry("mtu", setting->mtu());
}

QMap<QString,QString> WiredPersistence::secrets() const
{
  QMap<QString,QString> map;
  return map;
}

void WiredPersistence::restoreSecrets(QMap<QString,QString> secrets) const
{
  if (m_storageMode == ConnectionPersistence::Secure) {
  Q_UNUSED(secrets);
  }
}
