// This file is generated by kconfig_compiler from 802-11-wireless-security.kcfg.
// All changes you do to this file will be lost.
#ifndef WIRELESSSECURITYDBUS_H
#define WIRELESSSECURITYDBUS_H

#include <nm-setting-802-11-wireless-security.h>

#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "settingdbus.h"
#include "knm_export.h"
class WirelessSecuritySetting;

class KNM_EXPORT WirelessSecurityDbus : public SettingDbus
{
  public:
    WirelessSecurityDbus( WirelessSecuritySetting * setting);
    ~WirelessSecurityDbus();
    void fromMap(const QVariantMap&);
    QVariantMap toMap();
    QVariantMap toSecretsMap();
};
#endif

