// This file is generated by kconfig_compiler from 802-11-wireless-security.kcfg.
// All changes you do to this file will be lost.

#include "802-11-wireless-securitypersistence.h"

#include "802-11-wireless-security.h"

using namespace Knm;

WirelessSecurityPersistence::WirelessSecurityPersistence(WirelessSecuritySetting * setting, KSharedConfig::Ptr config, ConnectionPersistence::SecretStorageMode mode) : SettingPersistence(setting, config, mode)
{
}

WirelessSecurityPersistence::~WirelessSecurityPersistence()
{
}

void WirelessSecurityPersistence::load()
{
  WirelessSecuritySetting * setting = static_cast<WirelessSecuritySetting *>(m_setting);
  setting->setKeymgmt(m_config->readEntry("keymgmt", 0));
  setting->setWeptxkeyindex(m_config->readEntry("weptxkeyindex", 0));
  setting->setAuthalg(m_config->readEntry("authalg", 0));
  setting->setProto(m_config->readEntry("proto", QStringList()));
  setting->setPairwise(m_config->readEntry("pairwise", QStringList()));
  setting->setGroup(m_config->readEntry("group", QStringList()));
  setting->setLeapusername(m_config->readEntry("leapusername", ""));
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    setting->setWepkey0(m_config->readEntry("wepkey0", ""));
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    setting->setWepkey1(m_config->readEntry("wepkey1", ""));
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    setting->setWepkey2(m_config->readEntry("wepkey2", ""));
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    setting->setWepkey3(m_config->readEntry("wepkey3", ""));
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    setting->setPsk(m_config->readEntry("psk", ""));
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    setting->setLeappassword(m_config->readEntry("leappassword", ""));
  }
}

void WirelessSecurityPersistence::save()
{
  WirelessSecuritySetting * setting = static_cast<WirelessSecuritySetting *>(m_setting);
  m_config->writeEntry("keymgmt", setting->keymgmt());
  m_config->writeEntry("weptxkeyindex", setting->weptxkeyindex());
  m_config->writeEntry("authalg", setting->authalg());
  m_config->writeEntry("proto", setting->proto());
  m_config->writeEntry("pairwise", setting->pairwise());
  m_config->writeEntry("group", setting->group());
  m_config->writeEntry("leapusername", setting->leapusername());
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    m_config->writeEntry("wepkey0", setting->wepkey0());
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    m_config->writeEntry("wepkey1", setting->wepkey1());
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    m_config->writeEntry("wepkey2", setting->wepkey2());
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    m_config->writeEntry("wepkey3", setting->wepkey3());
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    m_config->writeEntry("psk", setting->psk());
  }
  // SECRET
  if (m_storageMode != ConnectionPersistence::Secure) {
    m_config->writeEntry("leappassword", setting->leappassword());
  }
}

QMap<QString,QString> WirelessSecurityPersistence::secrets() const
{
  WirelessSecuritySetting * setting = static_cast<WirelessSecuritySetting *>(m_setting);
  QMap<QString,QString> map;
  map.insert(QLatin1String("wepkey0"), setting->wepkey0());
  map.insert(QLatin1String("wepkey1"), setting->wepkey1());
  map.insert(QLatin1String("wepkey2"), setting->wepkey2());
  map.insert(QLatin1String("wepkey3"), setting->wepkey3());
  map.insert(QLatin1String("psk"), setting->psk());
  map.insert(QLatin1String("leappassword"), setting->leappassword());
  return map;
}

void WirelessSecurityPersistence::restoreSecrets(QMap<QString,QString> secrets) const
{
  if (m_storageMode == ConnectionPersistence::Secure) {
  WirelessSecuritySetting * setting = static_cast<WirelessSecuritySetting *>(m_setting);
    setting->setWepkey0(secrets.value("wepkey0"));
    setting->setWepkey1(secrets.value("wepkey1"));
    setting->setWepkey2(secrets.value("wepkey2"));
    setting->setWepkey3(secrets.value("wepkey3"));
    setting->setPsk(secrets.value("psk"));
    setting->setLeappassword(secrets.value("leappassword"));
    setting->setSecretsAvailable(true);
  }
}
