// This file is generated by kconfig_compiler from ppp.kcfg.
// All changes you do to this file will be lost.

#include "ppp.h"

PppSetting::PppSetting() : Setting(Setting::Ppp)
{
}

PppSetting::~PppSetting()
{
}

QString PppSetting::name() const
{
  return QLatin1String("ppp");
}
bool PppSetting::hasSecrets() const
{
  return false;
}
