// This file is generated by kconfig_compiler from vpn.kcfg.
// All changes you do to this file will be lost.
#ifndef VPNSETTING_H
#define VPNSETTING_H

#include <kglobal.h>
#include <kdebug.h>
#include <kcoreconfigskeleton.h>
#include "setting.h"
#include "knm_export.h"
class KNM_EXPORT VpnSetting : public Setting
{
  public:

    VpnSetting( );
    ~VpnSetting();

    QString name() const;

    bool hasSecrets() const;

    /**
      Set Service Type
    */
    void setServicetype( const QString & v )
    {
        mServicetype = v;
    }

    /**
      Get Service Type
    */
    QString servicetype() const
    {
      return mServicetype;
    }

    /**
      Set Data bits
    */
    void setData( const QString & v )
    {
        mData = v;
    }

    /**
      Get Data bits
    */
    QString data() const
    {
      return mData;
    }

    /**
      Set Username
    */
    void setUsername( const QString & v )
    {
        mUsername = v;
    }

    /**
      Get Username
    */
    QString username() const
    {
      return mUsername;
    }

    /**
      Set Routes
    */
    void setRoutes( const QStringList & v )
    {
        mRoutes = v;
    }

    /**
      Get Routes
    */
    QStringList routes() const
    {
      return mRoutes;
    }

  protected:

    // vpn
    QString mServicetype;
    QString mData;
    QString mUsername;
    QStringList mRoutes;

  private:
};

#endif

