// This file is generated by kconfig_compiler from pppoe.kcfg.
// All changes you do to this file will be lost.
#ifndef KNM_PPPOEPERSISTENCE_H
#define KNM_PPPOEPERSISTENCE_H

#include <kdebug.h>
#include "settingpersistence.h"
#include "internals/settings/pppoe.h"

namespace Knm {

class PppoeSetting;

class PppoePersistence : public SettingPersistence
{
  public:
    PppoePersistence( PppoeSetting * setting, KSharedConfig::Ptr config, SettingPersistence::SecretStorageMode mode = SettingPersistence::Secure);
    ~PppoePersistence();
    void load();
};
}

#endif

